### ISSUE TITLE
Question: How to use `DatadogTracingHttpClient` with `Dio`

### ISSUE THREAD

**Issue by ma-pe** [GetDutchie/datadog_flutter#47] opened 2021-08-24 10:05 UTC
Hi there, it's me again.

I am currently trying to use the `DatadogTracingHttpClient` together with `Dio`. The README.md suggested this is possible via Composition. Yet I am unable to get it to work. 

This is how far i have come already:

`Dio` allows to overwrite the `httpClientAdapter`:

```dart
  final client = Dio();

  client.httpClientAdapter = ... as HttpClientAdapter;
```

Yet I don't understand how to convert the `DatadogTracingHttpClient` which extends `http.BaseClient` to a `HttpClientAdapter`. 

Any help is much appreciated.

**Comment by tshedor** [comment] 2021-08-24 15:33
Hey @ma-pe . So looking at the Dio docs, you can [return a new HTTPClient when the Client adapter is initialized](https://github.com/flutterchina/dio#using-proxy). Because the method returns `dynamic`, I [verified that this is the case in the source](https://github.com/flutterchina/dio/blob/master/dio/lib/src/adapters/io_adapter.dart#L116-L117).

```dart
final client = Dio();
(client.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate = (_) => DatadogTracingHttpClient();
```

Also, quick plug: I maintain [Brick](https://github.com/greenbits/brick) which I find more straightforward than Dio. Give it a look if you're in the early stages of your app and you're using a REST API.

**Comment by ma-pe** [comment] 2021-09-06 16:32
@tshedor Good call!

I tried your proposal but did not get it to work. I am using the Interceptor and it's being called. Yet I don't find anything in Datadog as well as the response headers do not include the `x-datadog-parent-id`, so I cannot finish the span.

I also tried working with `DatadogRum.startResourceLoading` and `DatadogRum.stopResourceLoading` in the interceptors. I didn't get an error, but also didn't find data in datadog. :/

Both tests were done on the iOS.

**Comment by ma-pe** [comment] 2021-09-07 09:19
Regarding the latter (`DatadogRum. startResourceLoading`): 

the functions are executed, yet the SDK tells me there are no rum datasets to upload. So it seems to me that `DatadogRum. startResourceLoading()` is not functioning correctly on iOS.

This is my code:
```dart
class DatadogInterceptors extends Interceptor {
  @override
  Future<void> onRequest(
      RequestOptions options, RequestInterceptorHandler handler) async {
    await DatadogRum.startResourceLoading(
      'test1234',
      url: 'https://google.com',
      attributes: {'test': 'foobar'},
    );
    print('did execute `startResourceLoading(test1234)`');

    return super.onRequest(options, handler);
  }

  @override
  void onResponse(Response response, ResponseInterceptorHandler handler) {
    DatadogRum.stopResourceLoading(
      'test1234',
      statusCode: response.statusCode,
    );
    print('did execute `stopResourceLoading(test1234)`');

    return super.onResponse(response, handler);
  }
}
```

**Comment by tshedor** [comment] 2021-09-07 15:46
@ma-pe based on your code, the headers would not be added because it doesn't include the code I provided you in my comment. 

Regarding the start and stopping of resource loading, try removing the attributes and running. Regarding the appearance of resource loading logs in the DD backend, this [was recent issue that I confirmed does not exist with the right configuration](https://github.com/greenbits/datadog_flutter/issues/35#issuecomment-895581496); please make sure you're looking in the right place

**Comment by ma-pe** [comment] 2021-09-07 16:33
Hi @tshedor,

thank you for your support. When trying the headers I was using more or less exactly your code (filling the parameters accordingly). 

I also tried the resource loading without `attributes` - no effect. 

Maybe something about the configuration on init is not correct - because both features rely on RUM. Yet the Plugin/SDK is not really talkative 🙃

**Comment by tshedor** [comment] 2021-09-07 17:01
@ma-pe what is your code when using my code?

**Comment by ma-pe** [comment] 2021-09-08 08:57
This is the code I was testing the header-solution with:

```dart
class DatadogInterceptors extends Interceptor {
  @override
  Future<void> onRequest(
      RequestOptions options, RequestInterceptorHandler handler) async {

    final traceHeaders = await DatadogTracing.createHeaders(
      method: options.method,
      resourceName: options.path,
      url: options.uri.toString(),
    );
    
    options.headers.addAll(traceHeaders);
    // To make sure the generated traces from Real User Monitoring
    // don’t affect your APM Index Spans counts.
    // https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces/?tab=iosrum
    options.headers.addAll({'x-datadog-origin': 'rum'});
    print('request with interceptor');

    return super.onRequest(options, handler);
  }

  @override
  void onResponse(Response response, ResponseInterceptorHandler handler) {
    final spanId = response.headers['x-datadog-parent-id'];
    if (spanId != null) {
      // the native DD layer should not delay completion of the request
      // errors are also swallowed
      // ignore: unawaited_futures
      DatadogTracing.finishSpan(spanId, statusCode: response.statusCode)
          .catchError((_) => null);
      print('request answered with interceptor');
     }
     return super.onResponse(response, handler);
   }
}

```

**Comment by kevjose** [comment] 2021-12-04 12:12
@ma-pe fetching the `spanId` via `requestOptions` instead of `headers` would work here. And once, the `spanId` is passed it appears in the APM trace logs as well.

```
final spanId = response.requestOptions.headers['x-datadog-parent-id'];
```

**Comment by tshedor** [comment] 2022-02-07 18:52
Thanks @kevjose 

Closing with a recommendation for that ^ solution.

**Closed by tshedor** 2022-02-07 18:52 UTC
